//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClosetUI.Models.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClosetUI.Models.Locales.LocalizationResource", typeof(LocalizationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Actions_Add {
            get {
                return ResourceManager.GetString("Actions.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Actions_Calculate {
            get {
                return ResourceManager.GetString("Actions.Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Actions_Delete {
            get {
                return ResourceManager.GetString("Actions.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClosetUI.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string Direction_Horizontal {
            get {
                return ResourceManager.GetString("Direction.Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string Direction_Vertical {
            get {
                return ResourceManager.GetString("Direction.Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exterior.
        /// </summary>
        public static string HypotenuseType_Exterior {
            get {
                return ResourceManager.GetString("HypotenuseType.Exterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interior.
        /// </summary>
        public static string HypotenuseType_Interior {
            get {
                return ResourceManager.GetString("HypotenuseType.Interior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blade Thickness.
        /// </summary>
        public static string PartsGenerator_Input_BladeThickness {
            get {
                return ResourceManager.GetString("PartsGenerator.Input.BladeThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string PartsGenerator_Input_Direction {
            get {
                return ResourceManager.GetString("PartsGenerator.Input.Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HypotneuseType.
        /// </summary>
        public static string PartsGenerator_Input_HypotenuseType {
            get {
                return ResourceManager.GetString("PartsGenerator.Input.HypotenuseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string PartsGenerator_Input_Parts_Actions {
            get {
                return ResourceManager.GetString("PartsGenerator.Input.Parts.Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (mm).
        /// </summary>
        public static string PartsGenerator_Input_Parts_Height {
            get {
                return ResourceManager.GetString("PartsGenerator.Input.Parts.Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Name.
        /// </summary>
        public static string PartsGenerator_Input_Parts_Name {
            get {
                return ResourceManager.GetString("PartsGenerator.Input.Parts.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string PartsGenerator_Input_Parts_Qty {
            get {
                return ResourceManager.GetString("PartsGenerator.Input.Parts.Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width (mm).
        /// </summary>
        public static string PartsGenerator_Input_Parts_Width {
            get {
                return ResourceManager.GetString("PartsGenerator.Input.Parts.Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Height.
        /// </summary>
        public static string PartsGenerator_Input_TotalHeight {
            get {
                return ResourceManager.GetString("PartsGenerator.Input.TotalHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Width.
        /// </summary>
        public static string PartsGenerator_Input_TotalWidth {
            get {
                return ResourceManager.GetString("PartsGenerator.Input.TotalWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts List.
        /// </summary>
        public static string PartsGenerator_PartsListTitle {
            get {
                return ResourceManager.GetString("PartsGenerator.PartsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Generator Page.
        /// </summary>
        public static string PartsGenerator_Title {
            get {
                return ResourceManager.GetString("PartsGenerator.Title", resourceCulture);
            }
        }
    }
}
